### ISSUE TITLE
Reformat BibTex section

### ISSUE THREAD

**Issue by dinhanhx** [didadataset/DIDA#2]
https://github.com/didadataset/DIDA#bibtex

I suggest you to use [markdown block code](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) to format BibTex. For example:

```
@article{Kusetogullari2020DIDA, 
title={DIGITNET: A Deep Handwritten Digit Detection and Recognition Method Using a New Historical Handwritten Digit Dataset}, 
author={Huseyin Kusetogullari, Amir Yavariabdi, Johan Hall, Niklas Lavesson}, 
journal={Big Data Research}, year={2020} 
}
```

Also nice work

**Comment by didadataset** [comment]
> https://github.com/didadataset/DIDA#bibtex
> 
> I suggest you to use [markdown block code](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) to format BibTex. For example:
> 
> ```
> @article{Kusetogullari2020DIDA, 
> title={DIGITNET: A Deep Handwritten Digit Detection and Recognition Method Using a New Historical Handwritten Digit Dataset}, 
> author={Huseyin Kusetogullari, Amir Yavariabdi, Johan Hall, Niklas Lavesson}, 
> journal={Big Data Research}, year={2020} 
> }
> ```
> 
> Also nice work

Thank you for your comment
