### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by kromy** [didadataset/DIDA#3]
Thank you for you significant effort!

I can notice from related paper that the tool DIGITNET is used to detect and classify digits. however, the data i see here is only images with out any label. 

how can it be used for detection or classification?

**Comment by didadataset** [comment]
Dear Kromy 

Soon we will share a sample code for digit recognition using DIDA. For now you can follow the steps in the following link: https://www.kaggle.com/gpiosenka/features-a-custom-callback-you-may-like-to-use.

**Comment by didadataset** [comment]
> Thank you for you significant effort!
> 
> I can notice from related paper that the tool DIGITNET is used to detect and classify digits. however, the data i see here is only images with out any label.
> 
> how can it be used for detection or classification?

Dear Kromy

Soon we will share a sample code for digit recognition using DIDA. For now you can follow the steps in the following link: https://www.kaggle.com/gpiosenka/features-a-custom-callback-you-may-like-to-use.
